export const wordSearchGame = {
    matrix: [
        ['C', 'A', 'T', 'S', 'O', 'N', 'D', 'I', 'E', 'S'],
        ['E', 'L', 'I', 'Z', 'A', 'B', 'E', 'T', 'H', 'Y'],
        ['P', 'O', 'E', 'T', 'S', 'O', 'S', 'C', 'E', 'N'],
        ['T', 'H', 'I', 'N', 'E', 'W', 'O', 'R', 'D', 'O'],
        ['S', 'O', 'L', 'E', 'M', 'E', 'L', 'O', 'T', 'O'],
        ['B', 'O', 'O', 'K', 'E', 'N', 'W', 'I', 'N', 'D'],
        ['R', 'A', 'T', 'H', 'A', 'Y', 'O', 'O', 'D', 'S'],
        ['D', 'A', 'W', 'N', 'G', 'R', 'E', 'E', 'N', 'O'],
        ['E', 'L', 'M', 'N', 'E', 'E', 'B', 'A', 'C', 'K'],
        ['R', 'E', 'D', 'S', 'I', 'E', 'R', 'D', 'O', 'S'],
    ],
    words: [
        'CATS',
        'ELIZABETH',
        'POETS',
        'THINE',
        'SOME',
        'BOOK',
        'RATHAY',
        'DAWN',
        'ELM',
        'RED',
    ],
};
